version: '3'

volumes:
  db-data:

services:
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile.prod
    # depends_on:
    #   - db
    volumes:
      - ./:/var/www
      - ./vendor/bin:/var/www/html/vendor/bin
    ports:
      - ${WEB_PORT}:80
    environment:
      - APP_NAME=__APP_NAME__
      - DEBUG=${DEBUG}
      - APP_ENCODING=${APP_ENCODING}
      - APP_DEFAULT_LOCALE=${APP_DEFAULT_LOCALE}
      - APP_DEFAULT_TIMEZONE=${APP_DEFAULT_TIMEZONE}
      - SECURITY_SALT=${SECURITY_SALT}
      - OPENWEATHER_ONEDAY_URL=${OPENWEATHER_ONEDAY_URL}
      - OPENWEATHER_FIVEDAYS_URL=${OPENWEATHER_FIVEDAYS_URL}
      - OPENWEATHER_KEY=${OPENWEATHER_KEY}
      - NEWSAPI_URL=${NEWSAPI_URL}
      - NEWSAPI_KEY=${NEWSAPI_KEY}

  # db:
  #   image: mysql:5.7
  #   volumes:
  #     - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
  #     - db-data:/var/lib/mysql
  #   environment:
  #     - MYSQL_DATABASE=${DB_NAME}
  #     - MYSQL_USER=${DB_USER}
  #     - MYSQL_PASSWORD=${DB_PASS}
  #     - MYSQL_ROOT_PASSWORD=${DB_PASS}
  #   ports:
  #     - ${DB_PORT}:3306
  #   restart: always

