name: CI

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    env:
        WEB_PORT: ${{ secrets.WEB_PORT }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASS=: ${{ secrets.DB_PASS }}
        DB_PORT: ${{ secrets.DB_PORT }}
        
        PMA_USER: ${{ secrets.PMA_USER }}
        PMA_PASS: ${{ secrets.PMA_PASS }}
        PMA_PORT: ${{ secrets.PMA_PORT }}

        DB_TEST_NAME: ${{ secrets.DB_TEST_NAME }}
        DB_TEST_USER: ${{ secrets.DB_TEST_USER }}
        DB_TEST_PASS: ${{ secrets.DB_TEST_PASS }}
        DB_TEST_PORT: ${{ secrets.DB_TEST_PORT }}

        PMA_TEST_USER: ${{ secrets.PMA_TEST_USER }}
        PMA_TEST_PASS: ${{ secrets.PMA_TEST_PASS }}
        PMA_TEST_PORT: ${{ secrets.PMA_TEST_PORT }}

        # APP_NAME: ${{ vars.APP_NAME }}
        DEBUG: ${{ vars.DEBUG }}
        APP_ENCODING: ${{ vars.APP_ENCODING }}
        APP_DEFAULT_LOCALE: ${{ vars.APP_DEFAULT_LOCALE }}
        APP_DEFAULT_TIMEZONE: ${{ vars.APP_DEFAULT_TIMEZONE }}
        SECURITY_SALT: ${{ secrets.SECURITY_SALT }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}

        OPENWEATHER_ONEDAY_URL: ${{ vars.OPENWEATHER_ONEDAY_URL }}
        OPENWEATHER_FIVEDAYS_URL: ${{ vars.OPENWEATHER_FIVEDAYS_URL }}
        OPENWEATHER_KEY: ${{ secrets.OPENWEATHER_KEY }}
        NEWSAPI_URL: ${{ vars.NEWSAPI_URL }}
        NEWSAPI_KEY: ${{ secrets.NEWSAPI_KEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Docker composer
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Start Docker Compose
      run: |
        docker-compose -f docker-compose_prod.yml up -d --build
        docker exec newsapp-cp4_php_1 composer update

    - name: Start PHPUnit     
      run: docker exec newsapp-cp4_php_1 vendor/bin/phpunit
    
    - name: Down docker-compose
      run: docker-compose down
  

    # - name: Run PHPUnit
    #   run: docker exec news_cakephp4_php_1 ./vendor/bin/phpunit
    
    # - name: Stop containers
    #   run: docker-compose down


    # - name: Run PHPUnit
    #   run: |
    #     docker exec news_cakephp4_php_1 bash
    #     vendor/bin/phpunit

           

  
