name: deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      WEB_PORT: ${{ secrets.WEB_PORT }}
      DB_NAME: ${{ secrets.JAWS_DATABASE }}
      DB_USER: ${{ secrets.JAWS_USERNAME }}
      DB_PASS=: ${{ secrets.JAWS_PASSWORD }}
      DB_PORT: ${{ secrets.JAWS_PORT }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

      PMA_USER: ${{ secrets.PMA_USER }}
      PMA_PASS: ${{ secrets.PMA_PASS }}
      PMA_PORT: ${{ secrets.PMA_PORT }}

      DB_TEST_NAME: ${{ secrets.DB_TEST_NAME }}
      DB_TEST_USER: ${{ secrets.DB_TEST_USER }}
      DB_TEST_PASS: ${{ secrets.DB_TEST_PASS }}
      DB_TEST_PORT: ${{ secrets.DB_TEST_PORT }}

      PMA_TEST_USER: ${{ secrets.PMA_TEST_USER }}
      PMA_TEST_PASS: ${{ secrets.PMA_TEST_PASS }}
      PMA_TEST_PORT: ${{ secrets.PMA_TEST_PORT }}

      APP_NAME: ${{ vars.APP_NAME }}
      DEBUG: false
      APP_ENCODING: ${{ vars.APP_ENCODING }}
      APP_DEFAULT_LOCALE: ${{ vars.APP_DEFAULT_LOCALE }}
      APP_DEFAULT_TIMEZONE: ${{ vars.APP_DEFAULT_TIMEZONE }}
      SECURITY_SALT: ${{ secrets.SECURITY_SALT }}

      OPENWEATHER_ONEDAY_URL: ${{ vars.OPENWEATHER_ONEDAY_URL }}
      OPENWEATHER_FIVEDAYS_URL: ${{ vars.OPENWEATHER_FIVEDAYS_URL }}
      OPENWEATHER_KEY: ${{ secrets.OPENWEATHER_KEY }}
      NEWSAPI_URL: ${{ vars.NEWSAPI_URL }}
      NEWSAPI_KEY: ${{ secrets.NEWSAPI_KEY }}
    steps:
        - name: Checkout repository
          uses: actions/checkout@v2
        
        # - name: Set up PHP
        #   run: |
        #     heroku update
        #     sudo apt-get update
        #     sudo apt-get install -y docker-compose
        #     docker-compose -f docker-compose_prod.yml up -d --build
        #     docker exec news_cakephp4_php_1 composer update
         
        - name: Set up Heroku
          uses: akhileshns/heroku-deploy@v3.12.14
          with:
            heroku_api_key: ${{secrets.HEROKU_API_KEY}}
            heroku_app_name: "news-cakephp4"
            heroku_email: ${{secrets.HEROKU_EMAIL}} 
        - run: |
            heroku update
            sudo apt-get update
            sudo apt-get install -y docker-compose
            docker-compose -f docker-compose_prod.yml up -d --build
            docker exec news_cakephp4_php_1 composer update  