name: deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout repository
          uses: actions/checkout@v3
   
        - name: Set up Heroku
          uses: akhileshns/heroku-deploy@v3.12.14
          with:
            heroku_api_key: ${{secrets.HEROKU_API_KEY}}
            heroku_app_name: "newsapp-cp4"
            heroku_email: ${{secrets.HEROKU_EMAIL}} 
            usedocker: true
            # procfile: "web: npm start"
           
        # - name: db migration
        #   run: docker exec newsapp-cp4_php_1 bin/cake migrations migrate

            # docker exec newsapp-cp4_php_1 composer update  
            
            
         # - name: Set up PHP
        #   run: |
        #     heroku update
        #     sudo apt-get update
        #     sudo apt-get install -y docker-compose
        #     docker-compose -f docker-compose_prod.yml up -d --build
        #     docker exec news_cakephp4_php_1 composer update